Tailwind css
CraftAcademy/crafty_laundry pull request #12
Opened 2019-03-01 15:43 UTC by aleciabenjamin

[Pivotal Tracker](https://www.pivotaltracker.com/n/projects/2315151/stories/164246410)

This branch includes styling to the "Landing", "Sign up" and "Log in" pages.

2019-03-01 15:45 UTC, yanqiuzhang approved these changes

2019-03-01 15:52 UTC, NiciP approved these changes

2019-03-03 10:57 UTC, NiciP commented on app/views/layouts/application.html.haml
> +
remove extra line pls

2019-03-03 10:58 UTC, NiciP commented on app/views/devise/sessions/new.html.erb
> +
remove extra line pls

2019-03-03 10:59 UTC, NiciP requested changes
Just remove 3 blank lines as below pls

2019-03-03 10:59 UTC, NiciP commented on app/views/devise/sessions/new.html.erb
> +
remove extra line pls

2019-03-03 15:11 UTC, faraznaeem requested changes

2019-03-03 15:11 UTC, faraznaeem commented on config/routes.rb
> +  default_url_options :host => "example.com"
What is this route?

2019-03-03 15:11 UTC, faraznaeem commented
Why isn't semaphore kicking in?

2019-03-03 15:13 UTC, aleciabenjamin commented on config/routes.rb
> +  default_url_options :host => "example.com"
When clicking on 'send a new password to this email' link we encountered a host/path issue.  This fixed it.

2019-03-03 15:19 UTC, aleciabenjamin commented on config/routes.rb
> +  default_url_options :host => "example.com"
Is there a different fix you'd like us to use?  Build has passed on semaphore.

2019-03-03 15:30 UTC, tochman approved these changes

2019-03-03 15:30 UTC, merged